version: "2"

services:
  traefik:
    image: traefik
    restart: always
    command: |-
      --logLevel=DEBUG
      --web
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entrypoints='Name:https Address::443 TLS'
      --docker
      --docker.domain=traefik
      --docker.exposedbydefault=false
      --acme
      --acme.entrypoint=https
      --acme.email=amq@users.noreply.github.com
      --acme.storage=acme.json
      --acme.ondemand=false
      --acme.onhostrule=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml
      - acme:/etc/traefik/acme

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.sam101.amq.space"
      - "traefik.frontend.entryPoints=http,https"

volumes:
  acme:
    driver: local
  portainer:
    driver: local

### https://github.com/containous/traefik/issues/1334