version: "3.1"

# mkdir -p /root/traefik-config
# touch /root/traefik-config/acme.json
# touch /root/traefik-config/traefik.toml

services:

  traefik:
    image: traefik:1.3.0-alpine
    command:
      - --web
      - --docker 
      - --docker.watch 
      - --docker.swarmmode 
      - --docker.domain=traefik
      - --docker.endpoint=unix:///var/run/docker.sock
      - --debug=true
      - --logLevel=DEBUG
      - --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker-stack-this/traefik-manager/traefik-config/acme.json:/var/run/acme.json
      - /root/docker-stack-this/traefik-manager/traefik-config/traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

networks:
  ntw_front:
    external: true