version: "3.1"

services:

  traefik:
    image: traefik:1.3.0-alpine
    command: 
      - --web 
      - --docker 
      - --docker.watch 
      - --docker.swarmmode 
      - --docker.domain=traefik
      - --acme
      - --acme.acmeLogging
      - --acme.onDemand
      - --acme.OnHostRule
      - --acme.caServer="https://acme-staging.api.letsencrypt.org/directory"
      - --acme.email="letsencrypt@xxxxx.net"
      - --acme.storage="/var/run/acme.json"
      - --acme.entrypoint="https"
      - --DefaultEntryPoints=http,https
      - --debug=true
      - --logLevel=DEBUG
      - --InsecureSkipVerify=true
      - --web.statistics
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /traefik-config/acme.json:/var/run/acme.json
      #- /traefik-config/traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

networks:
  ntw_front:
    external: true