version: "3"

services:
  nginx1:
    image: nginx:1.13.0-alpine
    networks:
      - ntw_front
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=nginx1"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/nginx1"
        - "traefik.docker.network=ntw_front"

  nginx2:
    image: nginx:1.13.0-alpine
    networks:
      - ntw_front
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=nginx2"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/nginx2"
        - "traefik.docker.network=ntw_front"
networks:
  ntw_front:
    external: true
