version: "3.1"

services:
  traefik:
    image: traefik:1.2.3-alpine
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /root:/traefik.toml

    labels:
      - "traefik.enable=false"
    networks:
      - ntw_front
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      
networks:
  ntw_front:
    external: true