version: "3.1"

services:
  proxy:
    image: traefik:1.2-alpine
    networks:
      - ntw_front
      - ntw_socket
    volumes:
      - /root/traefik-config/acme:/etc/traefik/acme:rw,Z
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockersocket
    labels:
      - "traefik.enable=false"
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    tty: true
    command:
      - --docker
      - --docker.EndPoint=http://dockersocket:2375
      - --docker.ExposedByDefault=false
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=traefik
      - --web
      - --logLevel=DEBUG

  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      - ntw_socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  ntw_front:
    external: true

networks:
  ntw_socket:
    external: true