version: "3"

services:
  who1:
    image: emilevauge/whoami
    networks:
      - ntw_front
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=who1"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/who1"
        - "traefik.docker.network=ntw_front"

networks:
  ntw_front:
    external: true

