version: "3.3"

networks:
  ntw_front:
    external: true

volumes:
  traefik-pub: {}

  traefik:
    image: traefik:1.4.0-rc4
    command: |-
      - --docker
      - --docker.swarmmode=true
      - --docker.domain=traefik
      - --web
    ports:
      - "80:80"
      - "8181:8080"
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker-stack-this/traefik-manager-noacme/traefik.toml:/etc/traefik/traefik.toml
    deploy:
      labels:
      - "traefik.enable=false"
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 64M

services:
  socat:
    image: devmtl/socatproxy:1.0A
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.20'
          memory: 16M
        reservations:
          cpus: '0.10'
          memory: 8M
      labels:
        - "traefik.enable=false"

  traefik:
    image: traefik:1.4.0-alpine
    networks:
      - ntw_front
    ports:
      - mode: ingress
        target: 80
        published: 80
      #- mode: ingress
      #  target: 443
      #  published: 443
      - "8181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- traefik-pub:/etc/traefik/acme
    command: --docker \
      --docker.swarmmode=true \
      --docker.endpoint=unix:///var/run/docker.sock \
      --docker.domain=traefik \
      --docker.watch=true \
      --docker.exposedbydefault=true \
      --entryPoints='Name:http' \
      --debug=true \
      --logLevel=WARN \
      --web \
      --web.metrics \
      --web.metrics.prometheus \
      --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" \
      --web.address=:8181
      #--acme.entrypoint=https \
      #--acme=true \
      #--acme.domains='${CLUSTER_PUBLIC_DOMAIN}' \
      #--acme.email=${ACME_EMAIL} \
      #--acme.ondemand=true \
      #--acme.onhostrule=true \
      #--acme.storage=/etc/traefik/acme/acme.json \
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.33'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
      labels:
        - "traefik.enable=false"

#devmtl/traefikfire:1.3.8A
#--docker.endpoint=unix:///var/run/docker.sock \
#--docker.endpoint=tcp://socat:2375 \

# no acme
#
# Inspired by https://github.com/containous/traefik/issues/766#issuecomment-335208880
#
# Log options: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# https://github.com/containous/traefik/commit/af9b63eaed828f1d548f404fc8b486dd592184e9
#
# by Pascal Andy | # https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#