version: '3.1'

services:

  portainer:
    image: portainer/portainer:1.14.1
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 20M
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.docker.network=ntw_front"
        - "traefik.weight=10"
        - "traefik.frontend.passHostHeader=true"

networks:
  ntw_front:
    external: true


# Inspired from https://github.com/portainer/portainer-compose/blob/master/docker-stack.yml
#
# by Pascal Andy 2017-09-20_21h37
# https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#