version: "3"

services:
  webapp-nginx-a:
    image: nginx:1.13.0-alpine
    networks:
      - ntw_front
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=webapp-nginx-a"
        - "traefik.frontend.rule=PathPrefixStrip:/webapp-nginx-a"
        - "traefik.port=80"
        - "traefik.docker.network=ntw_front"

  webapp-nginx-b:
    image: nginx:1.13.0-alpine
    networks:
      - ntw_front
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=webapp-nginx-b"
        - "traefik.frontend.rule=PathPrefixStrip:/webapp-nginx-b"
        - "traefik.port=80"
        - "traefik.docker.network=ntw_front"

networks:
  ntw_front:
    external: true
