defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$aOa8/cTk$tTsbxqbEiIWaRoZyzvM4n1"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "johnnyone@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

caServer = "https://acme-staging.api.letsencrypt.org/directory"