version: "3.1"

services:
  caddy1:
    image: abiosoft/caddy:0.10.2
    networks:
      - ntw_front
    labels:
      - "traefik.backend=caddy1"
      - "traefik.port=2015"
      - "traefik.frontend.rule=PathPrefixStrip:/caddy1/"
      - "traefik.docker.network=ntw_front"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure

networks:
  ntw_front:
    external: true