version: "3.1"

services:
  who1:
    image: emilevauge/whoami
    networks:
      - ntw_front
    labels:
      - "traefik.backend=who1"
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/who1/"
      - "traefik.docker.network=ntw_front"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]                                                   
      restart_policy:
        condition: on-failure

networks:
  ntw_front:
    external: true

